find_package(PCL REQUIRED)
include_directories(${PCL_INCLUDE_DIRS})
set(PCL_LIBRARIES_WITHOUT_VTK "")
foreach(library ${PCL_LIBRARIES})
    if(NOT library MATCHES "vtk")
        list(APPEND PCL_LIBRARIES_WITHOUT_VTK ${library})
    endif()
endforeach()
message(STATUS "PCL_LIBRARIES: ${PCL_LIBRARIES_WITHOUT_VTK}")
list(APPEND ALL_TARGET_LIBRARIES ${PCL_LIBRARIES_WITHOUT_VTK})